### ISSUE TITLE
老吴，有个bug，提交给你，接着上一个继续说

### ISSUE THREAD

**Issue by a272121742** [DoubleSpout/rrestjs#10]
上一个问题果然是治标不治本，在进行后面的时候，发现静态资源文件无法附带版本号等参数信息。例如
`/statis/js/comm/jquery.js?version=1.7.1`在提交的时候，jquery文件将不会被加载，而`/statis/js/comm/jquery.js`则可以被加载，如果无法在静态资源文件上加版本信息，则很难控制前端的缓存。希望该问题能解决，按照前端伙伴所说，以前貌似是可以的，不知道为什么升级到0.9.x之后就不允许了，是不是我修改了源代码的缘故。

**Comment by yss** [comment]
从上面可以看出你没有写自动打包上线脚本，而是手工去维护。
这个可以叫老吴，以及我们共同折腾一个类似的自动打包上线脚本，叫做最佳体验。

**Comment by a272121742** [comment]
> 我们还没上线，只是在做开发阶段的时候，发现请求资源无法加入版本控制参数，加入后无法请求。
> 如果不加可以请求，但是没有了jq自身的版本控制功能，如果加了，却又无法请求，程序无法继续执行，纠结中。

**Comment by yss** [comment]
可以考虑这种方式，jquery.ab8c1235.js做为版本控制的。
比如取md5值的前8位

**Comment by yss** [comment]
通过你上面的描述应该是autoStatic.js解析js路径的问题导致的。
你这个issue都没有明确的标题指明到底是什么错误。
就直接“老吴，有个bug，提交给你，接着上一个继续说”，这样就感觉不像是issue了。；）

**Comment by DoubleSpout** [comment]
我在windows下试试看看~

**Comment by DoubleSpout** [comment]
v0.9.3版本已经发布，修复了这个在windows下存在的bug，和之前那个属于一个问题
