### ISSUE TITLE
[Bug]使用res.render('/xxx.jade', ..)时，jade模板地址只能是模板地址下的文件。

### ISSUE THREAD

**Issue by yss** [DoubleSpout/rrestjs#11]
比如使用res.render('/xxx/xxx.jade', ...)这样加一个目录层级的话，解析不了。

**Comment by DoubleSpout** [comment]
验证过了没有这个问题，可以放置子目录

**Comment by a272121742** [comment]
我证明，确实是可以的，不是框架的问题，你检查下是不是其他的问题。

**Comment by yss** [comment]
是我自己的问题。我写的jade里的extends xxx.jade路径不对

需要换成：../xxx.jade
