### ISSUE TITLE
[Improvement]改进combo模式的路径并且增加容错性

### ISSUE THREAD

**Issue by yss** [DoubleSpout/rrestjs#12]
目前对于静态文件的请求使用的方式是：

···html
/static/?parse=/static/js/a.js|/static/js/b.js
···
### 一、改进

能不能改进成这样子：

``` html
/static/js?parse=a.js|b.js
```

对应的css改进成：

``` html
/static/css?parse=a.css|b.css
```
### 二、容错

···html
/static/?parse=/static/js/a.js|/static/unknow.js
···
比如，没有unknow.js，还应该正确放回才对？

这里面又牵扯到了一个话题，如何防止自己的url被电信运营商劫持后依旧好使。

**Comment by DoubleSpout** [comment]
1、首先大包需要路径解析，所以在|的前后要放置我能找到的静态资源的路径，类似a.css我是无法查找静态资源的
2、容错，如果js不存在，或者包括语法错误，我认为是不应该通过的，这个问题再开发过程肯定会发现，不应该等上线才发现啊

**Comment by a272121742** [comment]
> 吴哥，他的第一点是可以实现的，这个我是作过的，因为/static只是你解析的一个标识，表示是静态资源文件，那么后面的parse解析成数组之后就应该默认在静态资源包里面去找。
> 第二点也是可以实现的，如果没有找到该资源，是不加入资源加载列的，即便他请求了也没有的。但是从开发上来讲确实不需要这个，是不是加个掉包处理会比较好点？

**Comment by DoubleSpout** [comment]
对于上面1,2点都是实现的，但是这个就是一个约定的东西，无所谓对错的~
