### ISSUE TITLE
[todo]  cluster监听的目录需要过滤一部分文件

### ISSUE THREAD

**Issue by DoubleSpout** [DoubleSpout/rrestjs#14]
进入开发模式，可以在config中设置一个数组用来例外cluster重启的后缀名。
比如设置了 
[.txt] 则表示当遇到后缀名为 .txt 的文件不重启进程

**Comment by yss** [comment]
默认处理的时候，应该或者说必须忽略一些临时文件。

我想到的处理是在 `lib/modules/ClusterPlus/lib/relode.js` 的fs.watch地方加上

``` javascript
// 忽略临时文件改动
if (/(?:\~|\.swo|\.swp|\.swn|\.swx|\.bak)$/.test(filename)) return;
```

这样处理后，少了很多次的服务重启。

**Comment by DoubleSpout** [comment]
已经将此加入配置文件了~THX
