### ISSUE TITLE
“整合压缩css或js文件的最大上限，建议不要超过15” - 不能理解

### ISSUE THREAD

**Issue by yss** [DoubleSpout/rrestjs#21]
default_config里有这么一条

``` javascript
staticParseMaxNumber:10,//整合压缩css或js文件的最大上限，建议不要超过15
```

为什么后面说是建议不要超过15，超过15会有什么问题呢？

**Comment by a272121742** [comment]
这只是建议不要超过15，当然你可以超过15，比如200个js文件都只有1kb，和1个文件就有几M，压缩当然是后者会消耗性能，所以这里我的理解就是只是建议。压缩本身就是牺牲性能见小体积的，所以使用需要恰当和谨慎！这只是我的理解，求老吴补充！

**Comment by DoubleSpout** [comment]
这个15是建议值，有如下2方面考虑
1、一般网站15个js或者css合并已经足够满足了，所以建议设置为15，当然你也可以20，甚至100
2、出于安全的考虑，如果设置了100，恶意用户就可能通过改变url路径或者挂参数，重复请求你100个整合的js路径，这样你的rrestjs框架会认为都是新的缓存，从而去获取这100个文件然后压缩编译整合，造成CPU无故消耗，如果请求数一多，可能down机或者拒绝服务了
所以综合考虑15个左右吧

**Comment by yss** [comment]
嗯，大致理解了。

**Comment by yss** [comment]
通过修改autoStatic.js我总算是明白过来的，这个参数的意义就是最大合并的js个数。
而不是我理解里的，只能是15种情况使用/static
:ideograph_advantage:
