### ISSUE TITLE
req发送的一个小问题

### ISSUE THREAD

**Issue by a272121742** [DoubleSpout/rrestjs#22]
> 当我实现了旁路业务和核心业务分离之后，随之而来的就遇到一些列的麻烦和问题，程序会莫名其妙的告诉我`Error: Can't set headers after they are sent.`，通过一个案例测试出来，案例如下：
> 
> ``` javascript
> var http = require('http');
> var rrest = require('rrestjs');
> var server = http.createServer(function(req,res){
>     if(true){
>         res.send('123');
>     }
>     res.send('321');
> }).listen(80);
> ```
> 
> 当我打开浏览器输入`127.0.0.1`的时候，页面是显示`123`，但是后台报错
> 
> ``` javascript
> http.js:644
>     throw new Error('Can\'t set headers after they are sent.');
>           ^
> Error: Can't set headers after they are sent.
>     at ServerResponse.OutgoingMessage.setHeader (http.js:644:11)
>     at RestZlib.send (D:\projects\eclipse\node_modules\rrestjs\lib\RestZlib.js:20:7)
>     at Gzip.onEnd (zlib.js:153:5)
>     at Gzip.EventEmitter.emit (events.js:85:17)
>     at zlib.js:349:10
>     at Zlib.callback (zlib.js:439:13)
> ```
> 
> 这样的错误我在原生的写法里没有遇到过，于是我开始用原生写法如下案例测试
> 
> ``` javascript
> var http = require('http');
> var server = http.createServer(function(req,res){
>     if(true){
>         res.write(JSON.stringify({a:123}));
>         res.end();
>     }
>     res.write(JSON.stringify({a:321}));
>     res.end();
> }).listen(80);
> ```
> 
> 浏览器显示`{"a":123}`
> 好的，这没报错，这不是我所希望的，我反而希望他报错，于是我看了下之前的报错提示`Can't set headers after they are sent.`，翻译过来就是`他们已经发送，您无法设置headers`，难道发送后就不能设置headers了吗？于是我改进了原生代码，是这样的
> 
> ``` javascript
> var http = require('http');
> var server = http.createServer(function(req,res){
>     if(true){
>         res.writeHeader(200, {'Content-Type':'text/javascript;charset=UTF-8'})
>         res.write(JSON.stringify({a:123}));
>         res.end();
>     }
>     res.writeHeader(200, {'Content-Type':'text/javascript;charset=UTF-8'})
>     res.write(JSON.stringify({a:321}));
>     res.end();
> }).listen(80);
> ```
> 
> 结果是浏览器依然有显示后台也没报错，我很不甘心，于是我想，是不是要在发送后，设置点不一样的headers呢？继续改进原生的代码
> 
> ``` javascript
> var http = require('http');
> var server = http.createServer(function(req,res){
>     if(true){
>         res.writeHeader(200, {'Content-Type':'text/javascript;charset=UTF-8'})
>         res.write(JSON.stringify({a:123}));
>         res.end();
>     }
>     res.writeHead(200, {'Content-Length': 1024,'Content-Type': 'text/plain;charset=GBK' });
>     res.write(JSON.stringify({a:321}));
>     res.end();
> }).listen(80);
> ```
> 
> node似乎很智能啊，这样依然没有报错，我依然不甘心，我把关键字锁定在了`set`上，我想我是不是该调用setHeader方法呢，于是我这样
> 
> ``` javascript
> var http = require('http');
> var server = http.createServer(function(req,res){
>     if(true){
>         res.setHeader('Content-Type','text/javascript;charset=UTF-8');
>         res.write(JSON.stringify({a:123}));
>         res.end();
>     }
>     res.setHeader('Content-Length',1024);
>     res.setHeader('Content-Type','text/html;charset=GBK');
>     res.write(JSON.stringify({a:321}));
>     res.end();
> }).listen(80);
> ```
> 
> 好吧，其实我已经精疲力尽的写到这了，我真希望这个错误能重现，果然出现了，和rrestjs框架所报的错误一模一样，因此呢……
> 我的建议就是将setHeader都替换为writeHeader，这样他不会报错，而且一旦发送出去req是不会重发（后面的依然会执行，但不会重发）。
> 另外我想知道setHeader和writeHead的本质区别

**Comment by DoubleSpout** [comment]
因为rrestjs框架封装的 res.send 方法里有设置头部，比如缓存，gzip等。报告这个错误是你已经res.end() 之后再调用res.send方法所致，有几个办法可以避免它：
1、从程序上避免，避免res或者req贯穿整个流程，只在controller层或者称为action层保留res和req对象，其他地方不要调用，不然到处都是res.send你会抓狂的
2、如果不幸已经造成res和req到处泛滥了，你可以在res.send前加上判断，因为node的http.js源码中有一个res.isend 属性，好像是这个，具体你可以参考下源码，我有点忘记了，当调用 res.end 方法后，node会将这个属性设置为true，而初始是false，所以可以很方便的知道是否已经响应给客户端了。

对于res.setHeader 和 writeHeader 明天告诉你答案吧，要去看源码了~

**Comment by yss** [comment]
我也碰到类似的问题，很多时候是在条件判断的时候使用了res.redirect or res.render

结果发现的问题是，忘了加一个return;导致的。

我认为在开发模式下的这种情况下，可以返回错误，并让服务器中止

但是在正常模式下，只是报错，但是忽略这种错误。

上面只是我的想法哈~ :smile_cat:

**Comment by a272121742** [comment]
> @yys 因为我采用的是aop的思路，所以即时return也还会执行后面的。思路大致如下
> 假设我有更新的核心业务逻辑，传入参数为
> 
> ``` javascript
> data:{
>     id:id,              //id是要更新对象的主键
>     update:{         //update对象是要更新对象的设置值，更新哪些属性就提交哪些即可
>     }
> }
> ```
> 
> 比如这个核心业务是会被请求到/crm/user!update.html，也就是action文件夹下crm文件夹下的user文件的update方法，在经过此方法的时候，会经过2层旁路业务逻辑的验证：
> 1.首先是session验证，如果session存在未过期，并且session.user是存在的，则表示处于登录状态，可以执行更新
> 
> ``` javascript
> //局部代码
> if(!session || !session.user){
>     res.sendjson({err:'登录超时'});
> }
> ```
> 
> 2.再验证参数有效性，如果没有传入id，或者没有传入update对象，都进行错误提示，另外要自动删除update中如果带入的id
> 
> ``` javascript
> if(!param.id || !param.update){
>     res.sendjson({err:'参数不足'});
> }
> if(param.update.id){
>     delete param.update.id;
> }
> ```
> 
> 这2层旁路业务逻辑的执行顺序是这样的，先执行旁路1，再执行旁路2，最后执行核心业务逻辑，但是他们之间有个特点是，上层无法控制下层的终止。也就是说，我在旁路1那有个`return`，但并不能终止旁路2和后面核心业务的执行，旁路1和旁路2虽然是做了拦截，但一定会通过。因此`return`在我这个分层业务逻辑上并没有效果。
> 而我是写过原生的，以前也是没用过setHeader，所以很单纯的认为，只要发送了，就不会执行后面的重发，因此我就按照很传统的写法在进行。好处就是不用我写那么深层的if判断，也不用加return，即便旁路1发送了错误，执行到旁路2的时候也不会重发。
> 可是在rrestjs中这样使用，是会报错的。经过寻坑的过程，发现是setHeader和writeHead可能有一些区别，现在等待老吴@DoubleSpout 解释。

**Comment by a272121742** [comment]
@DoubleSpout  `res.isend` 属性未找到

**Comment by yss** [comment]
一种方法是在最外层加一个issend属性用于标识是否发送完了。
每次执行前判断一下。

**Comment by a272121742** [comment]
@yss  如你所说，我一开始就考虑到这种方式，但是这样的显示操作让我感觉到恶心。每个旁路业务逻辑都要取出这个属性并且判断是否已经发送，如果发送执行后面的代码，再在发送的地方设置这个属性为true，甚至到了核心业务同样要做这样的操作，既然做了分离，就希望旁路业务与核心业务之间是分离的，旁路与旁路之间是分离的，这样才能松散耦合。但如果res自己有识别机制，对于已经发送过请求就不再执行后面的代码，这样他的作用就等同于return的效果，代码上就不会出现那么多的判断了。

**Comment by DoubleSpout** [comment]
OutgoingMessage.prototype.end = function(data, encoding) {
  if (this.finished) {
    return false;
  }

... ...

是res.finished这个属性，嗯，我可以在rrestjs框架里加上这个判断，但是有些地方你还是得注意不要重复res.setHeader，不然还是会报错的

**Comment by DoubleSpout** [comment]
这个 res.finished 是node源码支持的，而且没有加下划线，说明不是私有的，你可以利用一下，代码可以这么写

res.finished && res.send(xxx)
