### ISSUE TITLE
rrestjs升级到0.9.4后，强制刷新后，css不能自动更新

### ISSUE THREAD

**Issue by yss** [DoubleSpout/rrestjs#23]
换个思路是不是可以在开发模式下，直接每次都去编译对应的less文件呢？ :coffee:

**Comment by yss** [comment]
还有就是在config中加入一个属性，比如：mode: 'development'
用于判断是否是开发模式及生产模式，而不是通过设置ClusterNum的值呢？

**Comment by DoubleSpout** [comment]
把缓存时间设置1秒，就可以了，你可以自定义dev_config来自定义开发模式的配置文件，上线的话，只要加载不同的config文件就可以了

**Comment by yss** [comment]
我设的是这个：`statciMaxAge: -1000`

**Comment by DoubleSpout** [comment]
设置正确即可啦~

**Comment by yss** [comment]
问题已查明，是因为系统升级，之前我自己改的规则是只要是.css后缀的直接判断为less
而现在的autoStatic.js里的判断有两个：.less.css 以及 .less
