### ISSUE TITLE
是不是应该修正config里的：statciMaxAge为staticMaxAge

### ISSUE THREAD

**Issue by yss** [DoubleSpout/rrestjs#24]
对待书写错误要毫不留情的修改。 :smile: 
但是修正的同时，还应兼容之前的版本。

**Comment by yss** [comment]
修改已同步到dev分支上去了。放到了checkConfig.js里处理兼容模式了。

**Comment by DoubleSpout** [comment]
修复了语法错误，不仅仅是那个checkConfig~谢谢啦
