### ISSUE TITLE
在使用/static?parse=...时，可以在config里配置是否需要压缩

### ISSUE THREAD

**Issue by yss** [DoubleSpout/rrestjs#26]
我个人感觉是让用户选择性的使用压缩方式，而不是直接调用。
像我，如果是上线的话，所有的js，css都会压缩的。
另外线上环境的话，是不需要处理less的。

**Comment by DoubleSpout** [comment]
如果你是开发就单独加载一个个js和css吧，等上线了再改成那样吧，不需要处理less这句话不能理解啊

**Comment by yss** [comment]
让用户通过配置，去判断是否使用uglifyjs和compressCss去压缩对应的/static?parse=..请求。

**Comment by DoubleSpout** [comment]
都整合了肯定得压缩啊，如果不想压缩就不要用整合啦~

**Comment by yss** [comment]
一般上线了都是压缩好的代码。
现在很多公司都自己开发上线脚本，其实很大部分就是关于静态资源的整合和压缩。
不能把压缩放到上线去处理，很耗CPU及内存的，而且影响性能。
