### ISSUE TITLE
为什么用ClusterNum:1来表示进入开发模式

### ISSUE THREAD

**Issue by yss** [DoubleSpout/rrestjs#27]
为什么在config里加上一个变量来表示开发模式以及生产模式呢？

**Comment by DoubleSpout** [comment]
历史遗留问题，本来我想实现多进程都进入开发模式的，可是没有实现，完美支持的只能开1个进程，开多个会出问题，目前无法解决啊

**Comment by yss** [comment]
还是加一个env参数来判断是否是开发环境还是生产环境吧。

**Comment by DoubleSpout** [comment]
准备增加启动 -d 或者 --dev 来进入生产环境，那个设置cluster为1不变
