### ISSUE TITLE
可以自動補齊樣版引擎副檔名嗎

### ISSUE THREAD

**Issue by aloha1003** [DoubleSpout/rrestjs#33]
你好，像一般用样版引擎都是直接用
res.render("index");
可是rrestjs

还要另外补齐，要寫成 res.render("index.jade");

沒有辦法做到自動根據config去補齊副檔名嗎

謝謝回答

**Comment by DoubleSpout** [comment]
这个可以有，下个版本patch

**Comment by DoubleSpout** [comment]
1.1.0版本新增此功能~
