### ISSUE TITLE
Buffer.concat() 使用不当，导致抛出“RangeError: targetStart out of bounds”异常

### ISSUE THREAD

**Issue by leizongmin** [DoubleSpout/rrestjs#35]
在文件 lib/apiReq.js 第32行

https://github.com/DoubleSpout/rrestjs/blob/master/lib/apiReq.js#L32

```
var buf =  Buffer.concat(rec_ary, rec_ary.length);
```

当 **rec_ary** 的长度大于1的时候，会导致抛出 **“RangeError: targetStart out of bounds”** 异常。

Node.js API文档中， Buffer.concat() 的第二个参数应为所有Buffer的总长度，而不是Buffer数组的长度。

```
var buf =  Buffer.concat(rec_ary, rec_leng);
```

参考：http://nodejs.org/api/buffer.html#buffer_class_method_buffer_concat_list_totallength

**Comment by yss** [comment]
老雷在rrestjs吗？什么项目呢？

**Comment by leizongmin** [comment]
不是我在用。
这个项目 https://github.com/zensh/jsgen 使用了rrestjs，在本地测试没有问题，上线的时候，发布很长的文章时会出现上面那个错误。
其原因是本地运行时 **rec_ary** 一直都是1，所以没有问题，而上线运行的时候，发布长的文章时 **rec_ary** 会大于1，就出错了。
我帮忙调试了一下，发现了这个问题。

**Comment by DoubleSpout** [comment]
老雷，谢谢啊，之前我一直使用一个第三方的buffer模块，这次改回原生的api是出现了这个问题，周一到单位修复一下，第二个参数是所有buf的总长度~不是数组长度，回头写篇文章纪念下这个bug。

**Comment by DoubleSpout** [comment]
已经修复此bug，谢谢~
