### ISSUE TITLE
cannot listen controller files change in node v0.8.1

### ISSUE THREAD

**Issue by yss** [DoubleSpout/rrestjs#4]
when use you app examples, and i change the files in controller folder.
ex, i input restlog.info('aaa');
then i refresh the browser.
but the console isnot output ''aaa'
is this problem caused by node v0.8.1 ?
can you test it?

-- the thought of the rrestjs is what i like very much, but not really stronger. thank you!

**Comment by DoubleSpout** [comment]
最近比较忙，我会尽快安装node-v0.8版本进行测试的，谢谢你~

**Comment by DoubleSpout** [comment]
已经发布了新版本，cluster已经支持0.8.3了，因为node的api改变了
