### ISSUE TITLE
NodeJS v0.10.24 执行npm install rrestjs出错

### ISSUE THREAD

**Issue by jutleo** [DoubleSpout/rrestjs#40]
错误信息如下：

```
$ npm install rrestjs
```

npm http GET https://registry.npmjs.org/rrestjs
npm http 304 https://registry.npmjs.org/rrestjs
npm http GET https://registry.npmjs.org/generic-pool/1.0.6
npm http GET https://registry.npmjs.org/jade/0.20.0
npm http GET https://registry.npmjs.org/mime/1.2.7
npm http GET https://registry.npmjs.org/mongodb/1.1.6
npm http GET https://registry.npmjs.org/log4js/0.6.0
npm http GET https://registry.npmjs.org/socket.io/0.8.7
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/ejs/0.8.2
npm http GET https://registry.npmjs.org/less/1.3.0
npm http GET https://registry.npmjs.org/should/0.6.0
npm http GET https://registry.npmjs.org/now/0.8.1
npm http GET https://registry.npmjs.org/http-proxy/0.8.5
npm http GET https://registry.npmjs.org/request/2.11.4
npm http GET https://registry.npmjs.org/commander/1.0.5
npm http GET https://registry.npmjs.org/mkdirp/0.3.4
npm http GET https://registry.npmjs.org/qs/0.5.1
npm http GET https://registry.npmjs.org/data2xml/0.8.0
npm http GET https://registry.npmjs.org/xml2js/0.2.3
npm http GET https://registry.npmjs.org/formidable/1.0.11
npm http 304 https://registry.npmjs.org/generic-pool/1.0.6
npm http 304 https://registry.npmjs.org/mime/1.2.7
npm http 304 https://registry.npmjs.org/jade/0.20.0
npm http 304 https://registry.npmjs.org/log4js/0.6.0
npm http 304 https://registry.npmjs.org/mongodb/1.1.6
npm http 304 https://registry.npmjs.org/socket.io/0.8.7
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http 304 https://registry.npmjs.org/less/1.3.0
npm http 304 https://registry.npmjs.org/ejs/0.8.2
npm http 304 https://registry.npmjs.org/should/0.6.0
npm http 304 https://registry.npmjs.org/now/0.8.1
npm http 304 https://registry.npmjs.org/commander/1.0.5
npm http 304 https://registry.npmjs.org/http-proxy/0.8.5
npm http 304 https://registry.npmjs.org/mkdirp/0.3.4
npm http 304 https://registry.npmjs.org/request/2.11.4
npm http 304 https://registry.npmjs.org/qs/0.5.1
npm http 304 https://registry.npmjs.org/formidable/1.0.11
npm http 304 https://registry.npmjs.org/data2xml/0.8.0
npm http 304 https://registry.npmjs.org/xml2js/0.2.3
npm http GET https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/sax
npm http GET https://registry.npmjs.org/socket.io-client/0.8.7
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/redis/0.6.7
npm http 304 https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/sax
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/async/0.1.15
npm http GET https://registry.npmjs.org/dequeue/1.0.3
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/bson/0.1.3
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/redis/0.6.7
npm http 304 https://registry.npmjs.org/socket.io-client/0.8.7
npm http 304 https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/node-proxy
npm WARN engine commander@0.2.1: wanted: {"node":">= 0.4.x < 0.7.0"} (current: {"node":"v0.10.24","npm":"1.3.21"})
npm http 304 https://registry.npmjs.org/dequeue/1.0.3
npm http 304 https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/async/0.1.15
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/bson/0.1.3
npm http 304 https://registry.npmjs.org/node-proxy
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/bindings

> bson@0.1.3 install /Users/leo/nodes/test/node_modules/rrestjs/node_modules/mongodb/node_modules/bson
> node install.js
# 

=                                                                              =
=  To install with C++ bson parser do <npm install mongodb --mongodb:native>   =
# =                                                                              =

npm http 304 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/xmlhttprequest/1.2.2
npm http GET https://registry.npmjs.org/websocket-client/1.0.0
npm http GET https://registry.npmjs.org/uglify-js/1.0.6
npm http 304 https://registry.npmjs.org/bindings

> node-proxy@0.7.0 install /Users/leo/nodes/test/node_modules/rrestjs/node_modules/now/node_modules/node-proxy
> node-gyp configure build

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

gyp: Error 1 running xcodebuild
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/leo/nodes/test/node_modules/rrestjs/node_modules/now/node_modules/node-proxy
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.2.2
npm http 304 https://registry.npmjs.org/websocket-client/1.0.0
npm http 304 https://registry.npmjs.org/uglify-js/1.0.6
npm ERR! node-proxy@0.7.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-proxy@0.7.0 install script.
npm ERR! This is most likely a problem with the node-proxy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-proxy
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "rrestjs"
npm ERR! cwd /Users/leo/nodes/test
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/leo/nodes/test/npm-debug.log
npm ERR! not ok code 0

**Comment by DoubleSpout** [comment]
node-gyp安装的问题，请正确安装node-gyp，py 2.7.3+，gcc，g++等
