### ISSUE TITLE
ejs渲染问题

### ISSUE THREAD

**Issue by zzjin** [DoubleSpout/rrestjs#7]
新版的ejs支持了include 方法

但是目前的0.7.2还不支持...

尝试替换git版的ejs之后发现提示:

``` shell
Error: filename option is required for includes
```

ejs的模版的用法:  

``` ejs
<% include public/header.ejs %>
```

如果有时间的话可以看看怎么intergrate到最新的代码.

**Comment by DoubleSpout** [comment]
明天去单位把github更新到最新的ejs模块
这个错误时因为没有传递 filename 参数导致
只需要在res.render()时传递filename参数，即模版的所在绝对地址或相对地址即可
