### ISSUE TITLE
老吴，有个bug，提交给你

### ISSUE THREAD

**Issue by a272121742** [DoubleSpout/rrestjs#9]
> 其实这个也不算bug，但是我们在做项目的时候，发现问题不再我们的代码中，而是在rrestjs框架中，这个问题也是一个历史遗留问题，很早就有的。
> 一开始拿到rrestjs框架的时候，发现他仅仅只是支持2层解析，也就是说`res.path`只能被解析成2层，那么对于三层或者多层结构就无法满足，例如java中/oa/user!list.html是寻找oa文件夹下的user文件，加载其中的list方法，这是三层的，当然也可以设置为多层的。以前我避开这个问题，我以为只在app.js中手动配置即可，因此我没有使用rrestjs默认的路由解析规则，而是自己进行的3层解析。
> 但是，升级到0.9.x之后，发现某些景钛资源文件诸如js、css等无法正确加载，经过长时间的调试，发现是在`RestBridge.js`的54行和`autoStatis.js`的43行有需要改进的地方。RestBirdge源代码是
> 
> ``` javascript
> else if(('/'+req.path[0]) === staticStr && (req.method === 'GET' || req.method === 'HEAD'))
> ```
> 
> 此问题在于req.path[0]，在面对多层结构例如`/static/js/comm/jquery.js`时候，不会抽离出`/statis`字样，而是直接获取`\statis\js\comm\jquery.js`，这样在比较的时候代码无法通过，静态资源无法显示，建议修改为
> 
> ``` javascript
> else if(req.url.indexOf(staticStr) === 0 && (req.method === 'GET' || req.method === 'HEAD'))
> ```
> 
> 而autoStatic也做了相应修改，但这些都是治标不治本的修改，根本的修改方式还应该增加路由的解析层级。

**Comment by yss** [comment]
对于三层解析，你可以这么写
``
exports.second = function(req, res) {
    route[req.path[2]](req, res);
};
var route =  {
    index: function(req, res) { ... },
    other: function(req, res){ ... }
}
··

**Comment by a272121742** [comment]
> 这样写确实是可以，但是面临的就是一个文件里面方法过多，维护困难。
> 我是采用的java解析方式，用`/项目名(文件夹)/模块名(文件)!方法名.html`来提交url，后来没有按照rrestjs本身的路由规则，是自己用原生的api解析的url。
> 但rrestjs本身应该提供多层级路由。
> 另外该问题重点要问问为什么静态资源加载不了。

**Comment by DoubleSpout** [comment]
初步判定是由于windows下引起的问题，我再测试下看看是不是这个原因，不过之前在windows并没有出现此类问题呢

**Comment by DoubleSpout** [comment]
妹的找到问题的原因了，是这个函数引起的：normalize = require('path').normalize，具体原因我回去看了这个函数的源码应该可以得到！
可以肯定的说，这个函数在windows下是工作不正常的

**Comment by DoubleSpout** [comment]
v0.9.3版本已经发布，修复了这个在windows下存在的bug
